apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: geysermc-applications
spec:
  project: geyser-apps
  source:
    path: argo-cd-apps/production
    repoURL: git@github.com:GeyserMC/infra.git
    targetRevision: main
  destination:
    namespace: opencollab
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
